services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: attendance-management-db
    env_file:
      - cmd/api/app.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - attendance-network

  # Go Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-management-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - cmd/api/app.env
    environment:
      # Override DB_HOST to use service name (Docker network)
      DB_HOST: "postgres"
    ports:
      - "0.0.0.0:2754:2754"
    volumes:
      - .:/root/src
    networks:
      - attendance-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local


networks:
  attendance-network:
    driver: bridge
